org: adityaofficial10
app: the-big-bookshelf-api
service: the-big-bookshelf-api

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  environment:
    STRIPE_SECRET_KEY: sk_test_51Js0m8SIbQpOCQtjKNVtmdU9WIjNgeSNSLgvlZ4sJVxC1N4A0YKEMcpzhjyzNTdlgwjtmEfRfT24gIedHYumAyph00fZa1Chja
    PORT: 4000
    URI: mongodb+srv://aditya:223pMcifbx-BmCx@cluster0.vf340.mongodb.net/first?retryWrites=true&w=majority
    SECRET: mysecretkey
  stage: dev
  region: us-west-2
  timeout: 30

functions:
  verify-token:
    handler: middleware/auth.auth
  test:
    handler: controllers/buyers.test
    events:
      - http: 
          path: /buyers/test
          method: POST
          cors: true
          authorizer:
              name: verify-token
              identitySource: method.request.header.Authorization 
              resultTtlInSeconds: 3600
  register:
    handler: controllers/auth.register
    events:
      - http: 
          path: /auth/register
          method: POST
          cors: true
  login:
    handler: controllers/auth.login
    events:
      - http: 
          path: /auth/login
          method: POST
          cors: true
  purchase:
    handler: controllers/buyers.purchaseBook
    events:
      - http: 
          path: /buyers/purchase
          method: POST
          cors: true
          authorizer:
              name: verify-token
              identitySource: method.request.header.Authorization 
              resultTtlInSeconds: 3600
  feedback:
    handler: controllers/buyers.collectFeedback
    events:
      - http: 
          path: /buyers/feedback
          method: POST
          cors: true
          authorizer:
              name: verify-token
              identitySource: method.request.header.Authorization 
              resultTtlInSeconds: 3600
  updateProfile:
    handler: controllers/profile.updation
    events:
      - http: 
          path: /profile/update
          method: POST
          cors: true
          authorizer:
            name: verify-token
            identitySource: method.request.header.Authorization 
            resultTtlInSeconds: 3600
  getAll:
    handler: controllers/search.findAll
    events:
      - http: 
          path: /search/getAll
          method: GET
          cors: true
  getOne:
    handler: controllers/search.findQuery
    events:
      - http: 
          path: /search/getAll
          method: POST
          cors: true
  addBook:
    handler: controllers/sellers.addBook
    events:
      - http: 
          path: /sellers/add
          method: POST
          cors: true
          authorizer:
            name: verify-token
            identitySource: method.request.header.Authorization 
            resultTtlInSeconds: 3600
plugins:
  - serverless-offline
